### ISSUE TITLE
Add a namespace

### ISSUE THREAD

**Issue by nsoblath** [Electrostatics/geoflow_c#8]
Aside from it just being good C++ practice for code to be protected from name collisions using a namespace, there's an actual name collision between Geoflow and FETK/mc: the class (in Geoflow) and struct called `Mat`.

This naming conflict is a problem when both packages are used within APBS.

My proposed solution is to put all of Geoflow in a `geoflow` namespace.  It's a more limited codebase than FETK, which makes it much simpler to implement a namespace here.  And it's a "better" solution than preventing the use of Geoflow and FETK/mc together in APBS.

**Comment by sobolevnrm** [comment]
Sounds good to me!
